version: "3"

services:
  marcel_knowhow_backend:
    container_name: marcel_knowhow_backend
    image: marcel_knowhow_backend
    ports:
      - 8080:8000
    environment:
      - MARCEL_DB_URI=bolt://localhost:7687
    restart: unless-stopped 
    deploy:
      resources:
        limits:
          memory: 500m
