version: "3"

services:
  marcel_knowhhow_backend:
    container_name: marcel_knowhhow_backend
    image: jnicontainerregistry.azurecr.io/marcel_knowhhow_backend
    ports:
      - 8080:8000
    restart: unless-stopped 
    deploy:
      resources:
        limits:
          memory: 500m
